"""Scaffold templates for ``autodocs init``.

Contains the template strings and helpers that generate a ready-to-deploy
project setup in a single command.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Template: GitHub Actions workflow for GitHub Pages deployment
# ---------------------------------------------------------------------------

GITHUB_PAGES_WORKFLOW = """\
# Auto-generated by: autodocs init
# Builds documentation and deploys to GitHub Pages on every push to main.
#
# Setup required:
#   1. Go to repo Settings → Pages → Source → "GitHub Actions"
#   2. Add GROQ_API_KEY as a repository secret (Settings → Secrets → Actions)
#      Get a free key at https://console.groq.com

name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install autodocs
        run: pip install "autodocs[ai] @ git+https://github.com/ShivamBwaj/autodocs.git"

      - name: Generate documentation
        run: autodocs generate --source {source} --output _site --format html --ai --incremental
        env:
          GROQ_API_KEY: ${{{{ secrets.GROQ_API_KEY }}}}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{{{ steps.deployment.outputs.page_url }}}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
"""

# ---------------------------------------------------------------------------
# Template: .env.example
# ---------------------------------------------------------------------------

ENV_EXAMPLE = """\
# autodocs environment variables
# Copy this file to .env and fill in your values.

# Required for AI-powered docstring generation (free at https://console.groq.com)
GROQ_API_KEY=

# Optional: for Netlify deployment
# NETLIFY_TOKEN=
# NETLIFY_SITE_ID=
"""

# ---------------------------------------------------------------------------
# Entries to append to .gitignore
# ---------------------------------------------------------------------------

GITIGNORE_ENTRIES = [
    "# autodocs output",
    "_site/",
    "docs/",
    "build_report.json",
    ".autodocs_state.json",
]


# ---------------------------------------------------------------------------
# Scaffold helpers
# ---------------------------------------------------------------------------


def write_workflow(project_dir: Path, source: str = "./src") -> Path | None:
    """Create ``.github/workflows/autodocs.yml`` for GitHub Pages deployment.

    Returns the path to the created file, or None if it already exists.
    """
    workflow_dir = project_dir / ".github" / "workflows"
    workflow_path = workflow_dir / "autodocs.yml"

    if workflow_path.exists():
        return None

    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(
        GITHUB_PAGES_WORKFLOW.format(source=source),
        encoding="utf-8",
    )
    return workflow_path


def write_env_example(project_dir: Path) -> Path | None:
    """Create ``.env.example`` with placeholder environment variables.

    Returns the path to the created file, or None if it already exists.
    """
    env_path = project_dir / ".env.example"
    if env_path.exists():
        return None

    env_path.write_text(ENV_EXAMPLE, encoding="utf-8")
    return env_path


def update_gitignore(project_dir: Path) -> bool:
    """Append autodocs entries to ``.gitignore`` if not already present.

    Returns True if entries were added, False if they were already there.
    """
    gitignore_path = project_dir / ".gitignore"

    existing = ""
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")

    # Check if autodocs entries are already present
    if "# autodocs output" in existing:
        return False

    block = "\n" + "\n".join(GITIGNORE_ENTRIES) + "\n"
    with open(gitignore_path, "a", encoding="utf-8") as f:
        f.write(block)

    return True
